### ISSUE TITLE
route: route has not been found

### ISSUE THREAD

**Issue by dlangille** [mkjail/mkjail#21] opened 2021-08-04 13:47 UTC
This is a fresh install on a new host, mkjail 0.0.2

```
$ sudo mkjail create -h
route: route has not been found
usage: mkjail create [-j JAILNAME] [-a ARCH] [-v VERSION] [-f FLAVOUR] [-s "SETS"]

        -a Architecture (i386, amd64, etc)
	-f Flavour (copy in files after creation)
	-h View this help
	-j Jail name
	-s Sets: "base lib32"
	-v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

$ 
```

**Comment by feld** [comment] 2022-09-02 10:17
duplicate of #1

**Closed by feld** 2022-09-02 10:17 UTC
